environments:
  default:
    values:
      - env.yaml
---
helmDefaults:
  createNamespace: true
  skipDeps: true
releases:
  - name: home-cluster
    namespace: {{ .Values.namespace }}
    chart: ./home-cluster
    values:
      - ./values/home-cluster.yaml.gotmpl
  - name: local-path-provisioner
    namespace: {{ .Values.namespace }}
    chart: ./charts/local-path-provisioner
    values:
      - ./values/local-path-provisioner.yaml.gotmpl
  - name: redis
    namespace: {{ .Values.namespace }}
    chart: ./charts/redis
    values:
      - ./values/redis.yaml.gotmpl
    needs:
      - local-path-provisioner
  - name: gitea
    namespace: {{ .Values.namespace }}
    chart: ./charts/gitea
    values:
      - ./values/gitea.yaml.gotmpl
    needs:
      - ingress-nginx
      - local-path-provisioner
  - name: ingress-nginx
    namespace: {{ .Values.namespace }}
    chart: ./charts/ingress-nginx
    values:
      - ./values/ingress-nginx.yaml.gotmpl
